# Generated by Django 3.1.1 on 2020-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=255)),
                ('reserva', models.CharField(max_length=255)),
            ],
        ),
    ]
